function [vehicleTelem] = logToVehicleTelem(msqLogData)
%LOGTOVEHICLETELEM Summary of this function goes here
%   Detailed explanation goes here
VariableNames = {'t_offset','engineSpeed_rpm','tps','boost_psi'};
vehicleTelem = table( ...
    msqLogData.Time,...
    msqLogData.RPM,...
    msqLogData.TPS,...
    msqLogData.BoostPsi,...
    'VariableNames',VariableNames);
end

